apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - "./k8s/*"
build:
  local:
    concurrency: 0
    useDockerCLI: false
    push: false
  artifacts:
    - image: cloud10lms/gateway1
      context: ./server/gateway1
      docker:
        dockerfile: Dockerfile
        noCache: false
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: cloud10lms/integration
      context: ./server/integration
      docker:
        dockerfile: Dockerfile
        noCache: false
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: cloud10lms/manager
      context: ./server/manager
      docker:
        dockerfile: Dockerfile
        noCache: false
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: cloud10lms/user
      context: ./server/user
      docker:
        dockerfile: Dockerfile
        noCache: false
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: cloud10lms/tier
      context: ./server/tier
      docker:
        dockerfile: Dockerfile
        noCache: false
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
  