apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
spec:
  ingressClassName: nginx
  rules:
    - host: cloud10lms.com
      http:
        paths:
          - path: /api/v1/reservations
            pathType: Prefix
            backend:
              service:
                name: gateway1-srv
                port:
                  number: 5000
          - path: /api/v1/integrations
            pathType: Prefix
            backend:
              service:
                name: integration-srv
                port:
                  number: 6000
