import { Sidebar } from "@/components/Sidebar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="grid grid-cols-6">
          <div className="h-full col-span-1 ">
            <Sidebar />
          </div>
          <div className="h-full col-span-5 outline">{children}</div>
        </main>
      </body>
    </html>
  );
}
