apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: integration
  template:
    metadata:
      labels:
        app: integration
    spec:
      containers:
       - name: integration
         image: cloud10lms:integration